### PR TITLE
Update PolymorphicConverter.cs

### PR DESCRIPTION
**Pull request by dferretti**
After reading that thread you posted this example in and a bunch of other diving into all things system.text.json, I stumbled upon this
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#use-valuetextequals-for-property-name-lookups

I know you just threw this together as an example (which I found very useful!), but I think it could be worth noting that the ValueTextEquals method exists and can do property name comparisons without allocating strings with GetString(). 

When I went to pull the UTF8 bytes to a private field I figured I might as well pull the discriminator to a field too and let it be customizable, but feel free to ignore

Nice find on the Utf8ReaderJson copy trick!

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
Wow, I didn't think this sample code would get any PR, but thanks for posting this!
Indeed, I didn't know about that `ValueTextEquals` trick.
Now, it's my turn to suggest an edit to your code 🙂 : The `_discriminator` field could be removed (or replaced by the Utf8 one)

EDIT: my bad, it is used!

**Comment by jeremyVignelles** [comment]
Thanks for that 🙂

**Comment by dferretti** [comment]
No problem! I had similar thoughts as you in your message, wondering if something like this could work or if there was something overlooked. I started diving into the other related classes and thought maybe there would be a way to provide a ReadOnlySequence<byte> that is not rewindable or something to break it - it sounded like an IEnumerable sort of thing and it can be constructed with multiple sequences linked together. But even then it does look like you have to have all sequences on hand before starting the reader, so no harm there. Even the overload that takes in a Stream will read the whole stream into memory before deserializing. 
That coupled with the response that the system libraries use a similar strategy internally finally calmed me down haha - this seems like a very good solution.

**Comment by jeremyVignelles** [comment]
Indeed, while I'm more interested on implementing OneOf/AnyOf/AllOf in my project https://github.com/jeremyVignelles/Ooak , I might be interested in implementing that discriminated polymorphism later in there, to be able to fully support the OpenAPI spec (which allows that kind of polymorphism with a discriminator)

**Pull request merged**
